default: &default
  adapter: "postgresql"
  encoding: "unicode"
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "baseapp_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "baseapp_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "baseapp_production" } %>
